name: Build and Release

on:
  push:
    tags:
      - 'v*' # 监听以 v 开头的标签推送

permissions:
  contents: write # 必须赋予写权限，否则流水线无法自动在仓库创建 Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXEs
      run: |
        pyinstaller --onefile --name=Video7zPacker_General Pack_7z_general.py
        pyinstaller --onefile --name=Video7zPacker_Teleplay Pack_teleplay.py

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.exe # 一次性将刚才打包出的两个 exe 全部上传
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}